import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { createPublication, type Format } from "./publication.js";
import { loadPrintProfile } from "./profile-loader.js";
import { assertSealMatches } from "./seal.js";
import { BOOKFORGE_VERSION, run } from "./util.js";

export interface CheckOptions {
  /** Verify dist/release-seal.json against the current project (default false). */
  seal?: boolean;
  /** Refuse any chapter still marked draft (default false). */
  ship?: boolean;
}

const formatSchema = z.enum(["web", "epub", "pdf"]);
const hashSchema = z.string().regex(/^[a-f0-9]{64}$/);
const sourceSchema = z.enum(["built-in", "project"]);
const themeSchema = z.object({ id: z.string().min(1), version: z.string().min(1), hash: hashSchema, source: sourceSchema }).strict();
const printProfileSchema = z.object({ id: z.string().min(1), hash: hashSchema, source: sourceSchema }).strict();
const buildManifestSchema = z.object({
  bookforgeVersion: z.string().min(1),
  schemaVersion: z.literal(1),
  publicationId: z.string().min(1),
  sourceHash: hashSchema,
  theme: themeSchema,
  printProfile: printProfileSchema.optional(),
  toolVersions: z.record(z.string(), z.string()),
  formats: z.array(formatSchema).min(1).refine((formats) => new Set(formats).size === formats.length, "formats must not contain duplicates"),
  timestamp: z.string().min(1),
}).strict();

type CheckedManifest = z.infer<typeof buildManifestSchema>;

export async function checkProject(project: string, options: CheckOptions = {}): Promise<{ sections: number; assets: number }> {
  const root = path.resolve(project);
  const { publication, config, theme, sourceHash } = await createPublication(root);
  const dist = path.join(root, "dist");
  const manifest = await loadManifest(path.join(dist, "build-manifest.json"));
  const configuredFormats = Object.keys(config.outputs) as Format[];
  if (options.ship) {
    const draftChapters = config.chapters.filter((chapter) => chapter.status === "draft");
    if (draftChapters.length) {
      throw new Error(`Ship check refuses draft chapters: ${draftChapters.map((chapter) => chapter.id).join(", ")}. Mark them ready or locked.`);
    }
  }

  if (manifest.bookforgeVersion !== BOOKFORGE_VERSION) throw new Error(`Build manifest was generated by Bookforge ${manifest.bookforgeVersion}, not ${BOOKFORGE_VERSION}`);
  if (manifest.publicationId !== publication.id) throw new Error(`Build manifest publication ID does not match ${publication.id}`);
  if (manifest.sourceHash !== sourceHash) throw new Error("Build artifacts are stale: source hash does not match the current project");
  if (!sameFormats(manifest.formats, configuredFormats)) throw new Error(`Build manifest formats (${manifest.formats.join(", ")}) do not match configured outputs (${configuredFormats.join(", ")})`);
  if (!sameTheme(manifest.theme, theme)) throw new Error("Build manifest theme does not match the current project");

  let printProfile: Awaited<ReturnType<typeof loadPrintProfile>> | undefined;
  if (configuredFormats.includes("pdf")) {
    printProfile = await loadPrintProfile(root, config.outputs.pdf);
    if (!manifest.printProfile || manifest.printProfile.id !== printProfile.id || manifest.printProfile.hash !== printProfile.hash || manifest.printProfile.source !== printProfile.source) {
      throw new Error("Build manifest print profile does not match the current project");
    }
  } else if (manifest.printProfile) {
    throw new Error("Build manifest has a print profile but PDF is not configured");
  }

  if (options.seal) {
    await assertSealMatches(dist, {
      publication,
      sourceHash,
      theme,
      formats: manifest.formats,
      toolVersions: manifest.toolVersions,
      timestamp: manifest.timestamp,
      ...(printProfile ? { printProfile } : {}),
    });
  }

  if (configuredFormats.includes("web")) await checkWeb(dist, publication.spine.map((section) => section.id), config.outputs.web?.reading ?? "paged");
  if (configuredFormats.includes("epub")) await checkEpub(path.join(dist, "book.epub"));
  if (configuredFormats.includes("pdf")) await checkPdf(path.join(dist, "book.pdf"));
  return { sections: publication.spine.length, assets: publication.assets.length };
}

async function loadManifest(file: string): Promise<CheckedManifest> {
  await requireFile(file, "Build manifest");
  let parsed: unknown;
  try {
    parsed = JSON.parse(await readFile(file, "utf8"));
  } catch (error) {
    throw new Error(`Invalid build manifest JSON: ${error instanceof Error ? error.message : String(error)}`);
  }
  const result = buildManifestSchema.safeParse(parsed);
  if (!result.success) throw new Error(`Invalid build manifest: ${result.error.issues.map((issue) => `${issue.path.join(".") || "root"}: ${issue.message}`).join("; ")}`);
  return result.data;
}

async function checkWeb(dist: string, sectionIds: string[], reading: "paged" | "continuous"): Promise<void> {
  const web = path.join(dist, "web");
  await Promise.all([
    requireFile(path.join(web, "index.html"), "Web index"),
    requireFile(path.join(web, "reader.css"), "Web stylesheet"),
    requireFile(path.join(web, "reader.js"), "Web reader script"),
  ]);
  if (reading === "paged") await Promise.all(sectionIds.map((id) => requireFile(path.join(web, "chapters", `${id}.html`), `Web chapter ${id}`)));
}

async function checkEpub(file: string): Promise<void> {
  await requireFile(file, "EPUB artifact");
  const result = await run("epubcheck", [file], { quiet: true });
  if (result.code !== 0) throw new Error(`EPUBCheck failed:\n${result.stdout}${result.stderr}`);
}

async function checkPdf(file: string): Promise<void> {
  await requireFile(file, "PDF artifact");
  const result = await run("pdfinfo", [file], { quiet: true });
  const output = `${result.stdout}${result.stderr}`;
  if (result.code !== 0) throw new Error(`PDF validation failed:\n${output}`);
  const pages = output.match(/^Pages:\s*(\d+)\s*$/m)?.[1];
  if (!pages || Number(pages) < 1) throw new Error("PDF validation failed: PDF has no readable page count");
  if (!/^Page size:\s+\d/m.test(output)) throw new Error("PDF validation failed: PDF has no readable page size");
}

async function requireFile(file: string, label: string): Promise<void> {
  const info = await stat(file).catch(() => undefined);
  if (!info?.isFile()) throw new Error(`${label} is missing: ${file}`);
}

function sameFormats(actual: string[], expected: Format[]): boolean {
  return actual.length === expected.length && actual.every((format) => expected.includes(format as Format));
}

function sameTheme(manifestTheme: CheckedManifest["theme"], theme: Awaited<ReturnType<typeof createPublication>>["theme"]): boolean {
  return manifestTheme.id === theme.id && manifestTheme.version === theme.version && manifestTheme.hash === theme.hash && manifestTheme.source === theme.source;
}
