import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import type { PrintProfile, Publication, PublicationTheme } from "./model.js";
import { visitSection } from "./traversal.js";
import { BOOKFORGE_VERSION, defaultConcurrency, inlineText, mapPool, sha256 } from "./util.js";

const hashSchema = z.string().regex(/^[a-f0-9]{64}$/);
const chapterSnapshotSchema = z.object({
  id: z.string().min(1),
  title: z.string(),
  words: z.number().int().nonnegative(),
  digest: hashSchema,
}).strict();
const artifactSchema = z.object({
  path: z.string().min(1),
  bytes: z.number().int().nonnegative(),
  digest: hashSchema,
}).strict();

const sealSchema = z.object({
  schemaVersion: z.literal(1),
  kind: z.literal("bookforge-release-seal"),
  bookforgeVersion: z.string().min(1),
  publicationId: z.string().min(1),
  editionId: z.string().min(1).optional(),
  title: z.string().min(1),
  sourceHash: hashSchema,
  theme: z.object({ id: z.string(), version: z.string(), hash: z.string(), source: z.enum(["built-in", "project"]) }).strict(),
  printProfile: z.object({ id: z.string(), hash: z.string(), source: z.enum(["built-in", "project"]) }).strict().optional(),
  formats: z.array(z.enum(["web", "epub", "pdf"])).min(1),
  toolVersions: z.record(z.string(), z.string()),
  chapters: z.array(chapterSnapshotSchema),
  artifacts: z.array(artifactSchema),
  timestamp: z.string().min(1),
  contentDigest: hashSchema,
}).strict();

export type ReleaseSeal = z.infer<typeof sealSchema>;
export type ChapterSnapshot = ReleaseSeal["chapters"][number];

export interface SealExpectations {
  publication: Publication;
  sourceHash: string;
  theme: PublicationTheme;
  formats: Array<"web" | "epub" | "pdf">;
  toolVersions: Record<string, string>;
  timestamp: string;
  printProfile?: PrintProfile;
  editionId?: string;
}

export async function writeReleaseSeal(destination: string, input: SealExpectations): Promise<string> {
  const payload = canonicalPayload({
    schemaVersion: 1,
    kind: "bookforge-release-seal",
    bookforgeVersion: BOOKFORGE_VERSION,
    publicationId: input.publication.id,
    ...(input.editionId ? { editionId: input.editionId } : {}),
    title: input.publication.metadata.title,
    sourceHash: input.sourceHash,
    theme: themeIdentity(input.theme),
    ...(input.printProfile ? { printProfile: printProfileIdentity(input.printProfile) } : {}),
    formats: input.formats,
    toolVersions: input.toolVersions,
    chapters: snapshotChapters(input.publication),
    artifacts: await inventoryArtifacts(destination),
    timestamp: input.timestamp,
  });
  const seal: ReleaseSeal = { ...payload, contentDigest: digestPayload(payload) };
  const file = path.join(destination, "release-seal.json");
  await writeFile(file, `${JSON.stringify(seal, null, 2)}\n`);
  return file;
}

export async function loadReleaseSeal(file: string): Promise<ReleaseSeal> {
  const parsed: unknown = JSON.parse(await readFile(file, "utf8"));
  return sealSchema.parse(parsed);
}

export function snapshotChapters(publication: Publication): ChapterSnapshot[] {
  return publication.spine
    .map((section) => {
      let words = 0;
      const countWords = (value: string): void => {
        const trimmed = value.trim();
        if (trimmed) words += trimmed.split(/\s+/).length;
      };
      visitSection(section, {
        block: (block) => { if (block.type === "codeBlock") countWords(block.value); },
        inline: (inline) => {
          if (inline.type === "text" || inline.type === "code") countWords(inline.value);
        },
      }, { includeTitles: true });
      return {
        id: section.id,
        title: inlineText(section.title),
        words,
        digest: sha256(JSON.stringify(section)),
      };
    })
    .sort((left, right) => left.id.localeCompare(right.id));
}

export async function assertSealMatches(dist: string, expected: SealExpectations): Promise<ReleaseSeal> {
  const seal = await assertStoredSealMatchesArtifacts(dist);
  if (seal.bookforgeVersion !== BOOKFORGE_VERSION) {
    throw new Error(`Release seal was generated by Bookforge ${seal.bookforgeVersion}, not ${BOOKFORGE_VERSION}`);
  }
  const expectedIdentity = canonicalIdentity(expected);
  const actualIdentity = canonicalIdentityFromSeal(seal);
  if (JSON.stringify(actualIdentity) !== JSON.stringify(expectedIdentity)) {
    throw new Error("Release seal metadata does not match the current project and build manifest");
  }
  const chapters = snapshotChapters(expected.publication);
  if (JSON.stringify(seal.chapters) !== JSON.stringify(chapters)) {
    throw new Error("Release seal chapter snapshot does not match the current publication");
  }
  return seal;
}

export async function assertStoredSealMatchesArtifacts(dist: string): Promise<ReleaseSeal> {
  let seal: ReleaseSeal;
  try {
    seal = await loadReleaseSeal(path.join(dist, "release-seal.json"));
  } catch (error) {
    throw new Error(`Release seal is missing or incompatible; rebuild the project: ${errorMessage(error)}`);
  }
  const payload = canonicalPayload(seal);
  if (seal.contentDigest !== digestPayload(payload)) throw new Error("Release seal content digest does not match its metadata");
  const artifacts = await inventoryArtifacts(dist);
  if (JSON.stringify(seal.artifacts) !== JSON.stringify(artifacts)) {
    throw new Error("Release seal artifact inventory does not match dist contents");
  }
  return seal;
}

type SealPayload = Omit<ReleaseSeal, "contentDigest">;

function canonicalPayload(input: SealPayload | ReleaseSeal): SealPayload {
  return {
    schemaVersion: 1,
    kind: "bookforge-release-seal",
    bookforgeVersion: input.bookforgeVersion,
    publicationId: input.publicationId,
    ...(input.editionId ? { editionId: input.editionId } : {}),
    title: input.title,
    sourceHash: input.sourceHash,
    theme: { ...input.theme },
    ...(input.printProfile ? { printProfile: { ...input.printProfile } } : {}),
    formats: [...input.formats],
    toolVersions: sortedRecord(input.toolVersions),
    chapters: [...input.chapters].sort((left, right) => left.id.localeCompare(right.id)),
    artifacts: [...input.artifacts].sort((left, right) => left.path.localeCompare(right.path)),
    timestamp: input.timestamp,
  };
}

function digestPayload(payload: SealPayload): string {
  return sha256(JSON.stringify(canonicalPayload(payload)));
}

function canonicalIdentity(input: SealExpectations): object {
  return {
    publicationId: input.publication.id,
    ...(input.editionId ? { editionId: input.editionId } : {}),
    title: input.publication.metadata.title,
    sourceHash: input.sourceHash,
    theme: themeIdentity(input.theme),
    ...(input.printProfile ? { printProfile: printProfileIdentity(input.printProfile) } : {}),
    formats: [...input.formats],
    toolVersions: sortedRecord(input.toolVersions),
    timestamp: input.timestamp,
  };
}

function canonicalIdentityFromSeal(seal: ReleaseSeal): object {
  return {
    publicationId: seal.publicationId,
    ...(seal.editionId ? { editionId: seal.editionId } : {}),
    title: seal.title,
    sourceHash: seal.sourceHash,
    theme: { ...seal.theme },
    ...(seal.printProfile ? { printProfile: { ...seal.printProfile } } : {}),
    formats: [...seal.formats],
    toolVersions: sortedRecord(seal.toolVersions),
    timestamp: seal.timestamp,
  };
}

function themeIdentity(theme: PublicationTheme): ReleaseSeal["theme"] {
  return { id: theme.id, version: theme.version, hash: theme.hash, source: theme.source };
}

function printProfileIdentity(profile: PrintProfile): NonNullable<ReleaseSeal["printProfile"]> {
  return { id: profile.id, hash: profile.hash, source: profile.source };
}

async function inventoryArtifacts(root: string): Promise<ReleaseSeal["artifacts"]> {
  const entries = await readdir(root, { recursive: true, withFileTypes: true });
  const files = entries.flatMap((entry) => {
    const relative = path.relative(root, path.join(entry.parentPath, entry.name)).replaceAll("\\", "/");
    if (relative === "release-seal.json" || relative === "editions" || relative.startsWith("editions/")) return [];
    if (entry.isDirectory()) return [];
    if (!entry.isFile()) throw new Error(`Unsupported artifact entry in dist: ${relative}`);
    return [relative];
  });
  const artifacts = await mapPool(files, defaultConcurrency(16), async (relative) => {
    const contents = await readFile(path.join(root, relative));
    return { path: relative, bytes: contents.byteLength, digest: sha256(contents) };
  });
  return artifacts.sort((left, right) => left.path.localeCompare(right.path));
}

function sortedRecord(record: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(record).sort(([left], [right]) => left.localeCompare(right)));
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
