import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import type { BookConfig, PrintProfile, Publication, PublicationTheme } from "./model.js";
import { BOOKFORGE_VERSION, sha256, sourceEpochDate } from "./util.js";

const sealSchema = z.object({
  schemaVersion: z.literal(1),
  kind: z.literal("bookforge-release-seal"),
  bookforgeVersion: z.string().min(1),
  publicationId: z.string().min(1),
  editionId: z.string().min(1).optional(),
  title: z.string().min(1),
  sourceHash: z.string().regex(/^[a-f0-9]{64}$/),
  theme: z.object({ id: z.string(), version: z.string(), hash: z.string(), source: z.enum(["built-in", "project"]) }).strict(),
  printProfile: z.object({ id: z.string(), hash: z.string(), source: z.enum(["built-in", "project"]) }).strict().optional(),
  formats: z.array(z.enum(["web", "epub", "pdf"])).min(1),
  toolVersions: z.record(z.string(), z.string()),
  contentDigest: z.string().regex(/^[a-f0-9]{64}$/),
  timestamp: z.string().min(1),
}).strict();

export type ReleaseSeal = z.infer<typeof sealSchema>;

export async function writeReleaseSeal(destination: string, input: {
  publication: Publication;
  config: BookConfig;
  theme: PublicationTheme;
  sourceHash: string;
  formats: Array<"web" | "epub" | "pdf">;
  toolVersions: Record<string, string>;
  printProfile?: PrintProfile;
  editionId?: string;
}): Promise<string> {
  const seal: ReleaseSeal = {
    schemaVersion: 1,
    kind: "bookforge-release-seal",
    bookforgeVersion: BOOKFORGE_VERSION,
    publicationId: input.publication.id,
    ...(input.editionId ? { editionId: input.editionId } : {}),
    title: input.publication.metadata.title,
    sourceHash: input.sourceHash,
    theme: { id: input.theme.id, version: input.theme.version, hash: input.theme.hash, source: input.theme.source },
    ...(input.printProfile ? { printProfile: { id: input.printProfile.id, hash: input.printProfile.hash, source: input.printProfile.source } } : {}),
    formats: input.formats,
    toolVersions: input.toolVersions,
    contentDigest: sha256(JSON.stringify({
      id: input.publication.id,
      title: input.publication.metadata.title,
      spine: input.publication.spine.map((section) => section.id),
      sourceHash: input.sourceHash,
      theme: input.theme.hash,
    })),
    timestamp: sourceEpochDate().toISOString(),
  };
  const file = path.join(destination, "release-seal.json");
  await writeFile(file, `${JSON.stringify(seal, null, 2)}\n`);
  return file;
}

export async function loadReleaseSeal(file: string): Promise<ReleaseSeal> {
  const parsed: unknown = JSON.parse(await readFile(file, "utf8"));
  return sealSchema.parse(parsed);
}

export async function assertSealMatches(dist: string, sourceHash: string, publicationId: string): Promise<ReleaseSeal> {
  const seal = await loadReleaseSeal(path.join(dist, "release-seal.json"));
  if (seal.bookforgeVersion !== BOOKFORGE_VERSION) {
    throw new Error(`Release seal was generated by Bookforge ${seal.bookforgeVersion}, not ${BOOKFORGE_VERSION}`);
  }
  if (seal.publicationId !== publicationId) throw new Error("Release seal publication ID does not match the current project");
  if (seal.sourceHash !== sourceHash) throw new Error("Release seal is stale: source hash does not match the current project");
  return seal;
}
